language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode

branches:
  except:
    - experimental

branches:
  only:
    - master
    - develop

notifications:
  recipients:
    - jeffnyman@gmail.com

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
